name: RDB

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # 10 instance cho 10 job song song

    steps:
      - name: Create Windows User
        run: |
          $username = "newuser${{ matrix.instance }}"
          $password = ConvertTo-SecureString "Duythanh123." -AsPlainText -Force
          New-LocalUser -Name $username -Password $password -FullName "New User ${{ matrix.instance }}" -Description "User ${{ matrix.instance }}" -AccountNeverExpires

      - name: Grant Admin Rights
        run: Add-LocalGroupMember -Group "Administrators" -Member "newuser${{ matrix.instance }}"

      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

      - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # - name: Install dependencies
      #   run: |
      #     pip install PyAutoGUI opencv-python

      - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

      - name: Download ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Extract ngrok
        run: Expand-Archive ngrok.zip

      - name: Auth ngrok
        run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Create Tunnel
        run: .\n
